/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testsAddsNumber() {
        assertEquals(5, App.addNumbers(3, 2));
        assertEquals(1, App.addNumbers(-0, 1));
    }


    @Test
    public void reversesArray() {
        int[] results = App.reverse(new int[]{1, 2, 3,});
        assertEquals(3, results.length);
        assertArrayEquals(new int[]{1, 2, 3}, results);
    }

    @Test
    public void reversesEmptyArray() {
        int[] results = App.reverse(new int[]{});
        assertEquals("Reverses empty has wrong length", 0, results.length);
        assertArrayEquals(new int[]{}, results);
    }
}
