/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

public class App {

    public static void main(String[] args) {

        Flower f = new Flower("Bract");

        f.pet = new Rock("Rocky");

        System.out.println(f.pet);

        f.pet.numOfDiamonds = 2;

        System.out.println(f.pet.numOfDiamonds);

        Rock rocky = f.pet;
        f.pet = new Rock("Rocko");

        System.out.println(f.pet);
        System.out.println(rocky);

        doDomething(rocky);
        System.out.println(rocky);

        addDiamonds(rocky);
        System.out.println(rocky.numOfDiamonds);
    }

    public static void quickBigO() {
        int[] myFancyArray = new int[10];

        int x = myFancyArray[2];

        for (int i : myFancyArray) {
            System.out.println(i);
        }

        HashSet<Integer> set = new HashSet<>();

        for (int i : myFancyArray) {
            for (int j : myFancyArray) {
                set.add(i);
                System.out.println(j);
            }
        }
    }

    public static void doDomething(final Rock r) {
//        r = new Rock("Dome");

        final int x = 5;
    }

    public static void addDiamonds(Rock r) {
        r.numOfDiamonds++;
    }

    public static void reviewStuff() {
        Path path = Paths.get("names.txt");

        try (BufferedReader reader = Files.newBufferedReader(path)) {
//            List<String> lines = Files.readAllLines(path);
            String line = reader.readLine();
            while (line != null) {
                line = reader.readLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        ArrayList<String> list = new ArrayList<>();

        list.add("Hello");

        List<String> listconcept = list;

        list.remove("Hello");
        list.size();

        for (String item : list) {
        }
    }
}
